### ISSUE TITLE
Wrong url to create a subscriber [outdated docs]

### ISSUE THREAD

**Issue by roelvan** [ems-api/docs#1]
This file: https://github.com/ems-api/docs/blob/3ef5f8df7dca19063642ee7312c7ae90d57d9847/source/includes/_subscribers.md

The url to create a sub "POST API-URL/lists/LIST-UNIQUE-ID/subscribers/create" is not working.
When I remove the "/create" at the end it works.

**Comment by twisted1919** [comment]
@roelvan - Thanks for pointing out.
@ghimes - can you please check and fix this?

**Comment by ghimes** [comment]
Hello, 
That is true, the "/create" part should not be there. I will fix it right away.

**Comment by twisted1919** [comment]
@ghimes - what is the status of this?

**Comment by ghimes** [comment]
This has been corrected: https://github.com/ems-api/docs/commit/5bc9952ba31c057a48343342840efb74586de827
